version: "3.3"

services:
  fake-db:
    build:
      context: .
    container_name: mongo-fakedb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - DB_NAME=aurora-test
    command:
volumes:
  mongo-data:
    driver: local
