version: '3.3'

services:
  mongo:
    build:
      context: .
    container_name: mongo-fakedb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db


volumes:
  mongo-data:
    driver: local
